id = "racket"
name = "Racket"
description = "Racket support, with syntax highlighting and the Racket language server."
version = "0.0.2"
schema_version = 1
authors = [
    "Mikayla Maki <mikayla@zed.dev>",
    "Lucas A. Paul <lucas.a.paul@proton.me>",
]
repository = "https://github.com/zed-industries/zed"

[grammars.racket]
repository = "https://github.com/zed-industries/tree-sitter-racket"
commit = "beb29de2b668110e69df0c6d51649c3e2c91d863"

[language_servers.racket]
name = "Racket LSP"
languages = ["Racket"]
